version: '3.8'

services:
  backend:
    build: ../backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db
      - mongodb
      - rabbitmq
      - redis

  frontend:
    build: ../frontend
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=development

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:5
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:6
    ports:
      - "6379:6379"